version: "3.7"

x-php-base-dev: &php-base-dev
  build:
    target: php_dev
  volumes:
    - ./:/var/www/html
    - $HOME/.composer:/var/www/.composer

services:
  php:
    <<: *php-base-dev
    environment:
      COMPOSER_HOME: /var/www/.composer
    command:
      - 'composer'
      - 'install'

  fpm:
    <<: *php-base-dev

  consumer:
    <<: *php-base-dev
