version: "3.7"

x-fpm: &base-fpm
  build:
    context: .
    args:
      COMPOSER_VERSION: 1.9
      PHP_VERSION: 7.4
  environment:
    MESSENGER_TRANSPORT_DSN: redis://redis:6379/messages
  volumes:
    - app:/var/www/html

services:
  fpm:
    <<: *base-fpm

  consumer:
    <<: *base-fpm
    command: bin/console messenger:consume

  nginx:
    image: nginx:1.16-alpine
    volumes:
      - app:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 80:80

  redis:
    image: redis:5-alpine
    ports:
      - 6379:6379

volumes:
  app: ~
