envs:
    path: /
    controller: App\Controller\ShowEnvs

push:
    path: /push
    controller: App\Controller\Push

consumptions:
    path: /consumptions
    controller: App\Controller\Consumptions
