apiVersion: v1
kind: Pod
metadata:
  namespace: test
  name: redis
  labels:
    service: redis
    app: back
    env: dev
spec:
  containers:
    - name: redis
      image: redis:5-alpine

---

apiVersion: v1
kind: Service
metadata:
  namespace: test
  name: redis
  labels:
    service: redis
    app: back
    env: dev
spec:
  type: NodePort
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: redis
  selector:
    service: redis
    app: back
    env: dev
