kind: ConfigMap
apiVersion: v1
metadata:
  namespace: test
  name: back-nginx
  labels:
    app: back
    env: dev
data:
  nginx.conf: |
    server {
      root /app/public;

      location / {
      try_files $uri /index.php$is_args$args;
      }

      location ~ ^/index\.php(/|$) {
        fastcgi_pass 127.0.0.1:9000;

        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root;
        internal;
      }

      location ~ \.php$ {
        return 404;
      }
    }

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: test
  name: back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: back
      env: dev
  template:
    metadata:
      labels:
        app: back
        env: dev
    spec:
      volumes:
        - name: shared-files
          emptyDir: {}
        - name: nginx-config-volume
          configMap:
            name: back-nginx
      containers:
        - name: fpm
          image: formation/back:latest
          imagePullPolicy: IfNotPresent
          lifecycle:
            postStart:
              exec:
                command:
                  - "sh"
                  - "-c"
                  - "cp -rp /var/www/html/. /app"
          volumeMounts:
            - name: shared-files
              mountPath: /app
          env:
            - name: APP_ENV
              value: dev
            - name: APP_DEBUG
              value: '0'
            - name: SHELL_VERBOSITY
              value: '0'
            - name: MESSENGER_TRANSPORT_DSN
              value: 'redis://redis:6379/messages'
        - name: nginx
          image: nginx:1.16-alpine
          imagePullPolicy: Always
          volumeMounts:
            - name: shared-files
              mountPath: /app
            - name: nginx-config-volume
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: nginx.conf
