apiVersion: batch/v1
kind: Job
metadata:
  namespace: test
  name: back-consumer
  labels:
    app: back
    env: dev
    service: consumer
spec:
  parallelism: 3
  template:
    metadata:
      name: back-consumer
      labels:
        app: back
        env: dev
        service: consumer
    spec:
      containers:
        - name: consumer
          image: formation/back:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: APP_ENV
              value: dev
            - name: APP_DEBUG
              value: '0'
            - name: SHELL_VERBOSITY
              value: '0'
            - name: MESSENGER_TRANSPORT_DSN
              value: 'redis://redis:6379/messages'
          args:
            - 'bin/console'
            - 'messenger:consume'
      restartPolicy: OnFailure
